---
- name: Setup Nginx and deploy Barista Cafe template
  hosts: all
  become: yes
  tasks:
    - name: Install required packages (nginx,unzip)
      ansible.builtin.apt:
        name:
          - nginx
          - unzip
          
         
        state: present
        update_cache: yes

    - name: Ensure Nginx is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Download the ZIP file from tooplate
      ansible.builtin.get_url:
        url: "https://www.tooplate.com/zip-templates/2137_barista_cafe.zip"
        dest: "/tmp/2137_barista_cafe.zip" 

    
    - name: Create /tmp/test directory if it doesn't exist
      ansible.builtin.file:
        path: /tmp/test
        state: directory
        mode: '0755'

    - name: Unzip the file
      ansible.builtin.unarchive:
        src: "/tmp/2137_barista_cafe.zip"   # فایل ZIP دانلود شده
        dest: "/tmp/test"       
        remote_src: yes   
              
    - name: Move files to Nginx root directory
      ansible.builtin.shell:
        cmd: rm -rf /var/www/html/* ; mv  /tmp/test/2137_barista_cafe/*  /var/www/html/
      become: yes  


    - name: Set permissions for web files
      ansible.builtin.file:
        path: "/var/www/html/"
        owner: root
        group: root
        recurse: yes
        mode: '0755'

    - name: Restart Nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
